services:
  sas_ur_robot_driver_tester_original:
    build: 
      context: .
      dockerfile: Dockerfile.original
    stop_signal: SIGINT
    stop_grace_period: 1m
    network_mode: "host"
    environment:
      - ROS_DOMAIN_ID=17
    cap_add:
      - SYS_NICE # PREEMPT_RT
    ulimits:
      rtprio: 99 # PREEMPT_RT
      rttime: -1 # PREEMPT_RT
    tty: true
    stdin_open: true
    command: /bin/bash -c "
      cd /root/ros2_ws/
      && source /opt/ros/jazzy/setup.bash
      && source install/setup.bash
      && export FASTRTPS_DEFAULT_PROFILES_FILE=/root/ros2_ws/src/sas_ur_control_template/docker/scripts/fastrtps_profile.xml
      && ros2 launch sas_ur_control_template robot_example_py_launch.py"